version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network
  backend:
    build: ./ody-backend
    ports:
      - "5000:5000"
    volumes:
      - ./ody-backend:/app
    environment:
      - FLASK_APP=odybackend.app
      - FLASK_ENV=development
    depends_on:
      - postgres
    networks:
      - backend-network
  frontend:
    build: ./ody-frontend
    ports:
      - "3001:80"
    
networks:
  backend-network:
    driver: bridge

volumes:
  pgdata: