# Generated by Django 4.1 on 2024-03-08 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FreeformAerobic',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.exercise')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
            bases=('workouts.exercise',),
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.exercise')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reps', models.IntegerField()),
            ],
            bases=('workouts.exercise',),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('freeformaerobic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.freeformaerobic')),
            ],
            bases=('workouts.freeformaerobic',),
        ),
        migrations.CreateModel(
            name='Swim',
            fields=[
                ('freeformaerobic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.freeformaerobic')),
                ('stroke', models.CharField(choices=[('FR', 'Freestyle'), ('BK', 'Backstroke'), ('BR', 'Breaststroke'), ('FL', 'Butterfly')], max_length=2)),
            ],
            bases=('workouts.freeformaerobic',),
        ),
    ]
